version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-auth-app
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'      # AMQP port
      - '15672:15672'    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
